// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NavBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!--====================================================================\n                                Start Header area\n        =====================================================================--><header class=\"main-header\"><div class=\"container\"><div class=\"header-inner\"><div class=\"main-logo\"><a href=\"/\"><img src=\"/static/images/logo.png\" alt=\"Logo\"></a></div><div class=\"search-btn\"><button><i class=\"flaticon-search\"></i></button></div><div class=\"menu-toggler\"><button><span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span></button></div><nav class=\"search-form\"><div class=\"search-close\"><button><i class=\"flaticon-cancel\"></i></button></div><form action=\"#\"><input type=\"search\" required placeholder=\"type here for search...\"> <button type=\"submit\"><i class=\"flaticon-search\"></i></button></form></nav><nav class=\"main-menu\"><div class=\"menu-close\"><button><i class=\"flaticon-cancel\"></i></button></div><ul><li><a href=\"/\">Home</a></li><li><a href=\"/about\">about me</a></li><li><a href=\"blog-details.html\">blog details</a></li><li><a href=\"/contact\">contact</a></li></ul></nav></div></div></header><!--====================================================================\n                                End Header area\n        =====================================================================-->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
